### ISSUE TITLE
getting an extra blank line when iterating over a slice

### ISSUE THREAD

**Issue by craigschmidt** [cessen/ropey#15]
I'm new to rust,  so sorry if I'm doing something dumb, but I'm seeing a weird bug.  When iterating over a slice with `lines`, I get an extra empty line.  If you make a new program with cargo like this, it fails.  However, I added the same test to ropey as a test in the iter.rs file, and it passed.  I don't understand how that can be.  

Thanks,
Craig

```rust
extern crate ropey;

use ropey::Rope;

fn main() {

    let text = "Hello there!\nHow goes it?";
    let rope = Rope::from_str(text);

    // should be the same as rope
    let slice = rope.slice(..);

    // but we get an extra empty line when iterating over the slice
    assert!(slice.lines().count() == rope.lines().count());
}


#[cfg(test)]
mod tests {
    use Rope;

    #[test]
    fn lines_from_slice() {
        
        let text = "Hello there!\nHow goes it?";
        let rope = Rope::from_str(text);

        // should be the same as rope
        let slice = rope.slice(..);

        // but we get an extra empty line when iterating over the slice
        assert!(slice.lines().count() == rope.lines().count());
    }

}
```

**Comment by craigschmidt** [comment]
My `Cargo.toml` looks like this:

```toml
[package]
name = "iterbug"
version = "0.1.0"
authors = ["Craig Schmidt <craig@craigschmidt.com>"]

[dependencies]
ropey = { git = "https://github.com/cessen/ropey", branch = "master" }
```
